config/routes.rb
Rails.application.routes.draw do
  
   resources :products do 
     member do
     get "trans"
     end
     collection do 
       put 'trans_pay'
     end
   end
   
   get "/sign_up" , :to=> "users#new"
   get 'users/login_page'
   put 'users/validate_login'
   get 'users/logout'
   resources :users 
   root to: "users#login_page"
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>", small: "200x200" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
                                                          #/\Aimage\/.jpg|.png|.gif\Z/
  # belongs_to :user
  # belongs_to :product 
  belongs_to :entity, :polymorphic => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :images, as: :entity
end
 # => 
# p = Product.last
# p.images => select * from images where entity_id = p.id and entity_type = 'Product'
# 
# 
# u = User.last
# u.image => select * from images where entity_id = u.id and entity_type = 'User'

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true,:format => /\D.*@gmail.com/
  validates :password, :presence => true, :length => {:minimum => 5, :maximum => 10}
  scope :first_record,  -> { self.all}
  has_one :image, as: :entity
  accepts_nested_attributes_for :image
  # validates :email_id
#   
  # def email_id
    # code
  # end
  before_validation do | user |
    if password.blank?
      self.password = "password"
      self.confirm_password = "password"
    end
  end
  
  before_save :change_name
  before_validation :verify_confirm_password
  before_save :encrypt_password
  
  def encrypt_password
   self.password = Digest::MD5.hexdigest(password)
   self.confirm_password =  Digest::MD5.hexdigest(confirm_password)
  end
  
  before_destroy :save_records
   def save_records
     File.open("#{Rails.root}/log/save_records.json", "a+") { |foo| foo.write(self.to_json)}
   end
  
  
  def verify_confirm_password
    if password != confirm_password
      errors.add(:base,  "Password and confirm password are not equal")
    end 
  end 
  def change_name
    self.name = "Hello ruby!"  
  end
  def self.authenticate(user_records)
    @user = User.where(:email => user_records[:email], :password =>Digest::MD5.hexdigest(user_records[:password])).last
    if @user 
      @user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  before_action :check_seesion
  
  before_action :first_me
  
  def check_seesion
    flash[:notice] =  "Hello I am here "   
  end
  
  def first_me
      flash[:notice] = "I am the top of every action" 
      puts "I am below of every action"   
  end
   before_action :check_session
   
   def check_session
     if session[:user_id].blank?
       redirect_to root_path
     end
   end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # changeasdsdfasdfasdfasd
  #using manav branch
  def pankaj
    # from third branch
  end
  def index
    @product = Product.all
  end

  def new
    @product = Product.new
  end
  def trans
    @product=Product.find(params[:id])
  end  
  def trans_pay
    
  current_user = User.find session[:user_id]
  @product=Product.find(params[:id])
  @result = Braintree::Transaction.sale(
  :amount => 5000,
  :credit_card => {:number => params[:user][:credit_card_number],
    :expiration_date => "#{params[:user]['date(2i)']}/#{params[:user]['date(1i)']}"},
    :options=> {store_in_vault: true }
    )
if @result.success?
current_user.update(braintree_customer_id: @result.transaction.customer_details.id)
redirect_to :action=>"index", notice: "Congraulations! Your transaction has been successfully!"
else
redirect_to :action=>"trans", notice: "Transaction fail"
end
end
  def create
    image_attributes = product_params[:image][:photo]
    product_params.delete(:image)
    @product = Product.new(product_params)
       if @product.save
         image_attributes.each do | image |
           Image.create!(:photo => image, :entity => @product )
         end
         redirect_to :action=>"index"
        flash[:notice] = "Successfully created user records :)"
        else
          render :new
     end
  end
  

  def edit
  end

  def show
  end
  private
  def product_params
    params.require(:product).permit!
  end
end

# belongs_to
# has_one
# has_many
# 
# has_one :through
# has_many :through
# has_and_belongs_to_many
# polymorphism
# STI



   # Image
    # /\/\
 # product user subscriber article
#  
#  
#  
 # polymorphism
#  
 # 1. first make the table as polymorphic true
 # 2. add the below two colum to the table
    # entity_id
    # entity_type
#     
 # 3. wherever you are wiling to use image tell that table to search based on entity not based on its own id.   

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  skip_before_action :first_me , :only => [:new, :create, :edit, :update, :destroy, :show]
  skip_before_action :check_session, :only => [:new, :create, :login_page, :validate_login]
 
  def index
    @user = User.paginate(:page => params[:page], :per_page => 5)
    logger = Logger.new("#{Rails.root}/log/manual_log.log")
    logger.info(@user)
    @user + []
  end

  def new
    @user = User.new
    @user.build_image
  end
  
  def create
    
    @user = User.new(user_params)
    respond_to do | format |
    if @user.save
      format.html do 
      #  session[:user_id] = @user.id
        EmailSend.welcome(@user, "Welcome to batch250 store").deliver!
        redirect_to :action=>"index"
        flash[:notice] = "Successfully created user records :)"
      end
      format.json  do
        render json: @user
      end 
    else
      format.html do
        render "new"
        flash[:notice] = "Opps something went wrong!"
      end
      format.json do 
        render json: {:status => "Opps something went wrong!"}
      end
       format.xml do 
        render xml: {:status => "Opps something went wrong!"}
      end
      
    end
    end
  end
  
  def edit
     @user = User.find params[:id]
  end
   def update
    @user = User.find params[:id]
    if @user.update_attributes(user_params)
      redirect_to :action=>"index"
      flash[:notice] = "Successfully updated user records :)"
    else
      render "new"
      flash[:notice] = "Opps something went wrong!"
    end
  end
  def show
     @user = User.find params[:id]
  end
  def destroy
    @user = User.find params[:id]
    @user.delete
    redirect_to :action=>"index"
    flash[:notice] = "Successfully deleted records :)"
  end
  def login_page
    @user = User.new
  end
  def validate_login
    @user = User.authenticate(user_params)  
    if @user 
      session[:user_id] = @user.id
      redirect_to :action => "index"
    else
      redirect_to :action => "login_page"
    end 
  end
  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
  private
  def  user_params
    params.require(:user).permit!
  end
end


#params = {}
#params = {:user={:name=>"", :email=>, :address=>""}}

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_email 
    (User.find session[:user_id]).email
  end
  def admin?
    (User.find session[:user_id]).email == "admin@gmail.com"
  end
  def return_user_object
    @user = (User.find session[:user_id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def display_name(name)
      "My name is #{name}"    
  end
  
end

app/views/email_send/welcome.html.erb
<h1>Welcome Email from Batch 250 store</h1>

<p><%= "Hi\n, Good to see you here, Please use the below code to avail 30% disscount on your first purchase.\n CODE : XZERY5612MTY \n Thanks,\n
Store Manager."%>
</p>

app/views/email_send/welcome.text.erb
EmailSend#welcome

<%= @greeting %>, find me in app/views/email_send/welcome.text.erb

app/views/layouts/_header.html.erb
<div class="btn-group btn-group-justified" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <a href="/users" type="button" class="btn btn-default">Home</a>
  </div>
  <div class="btn-group" role="group">
    <a href="/users/new" type="button" class="btn btn-primary">New Registration</a>
  </div>
  <div class="btn-group" role="group">
  	<%= link_to "Logout", users_logout_path, :class=>"btn btn-default" %>
  </div>
   <div class="btn-group" role="group">
  	<%= current_user_email %>
  </div>
</div>

<!-- nikhilatgur@gmail.com
pankajkhanna1@gmail.com
sidharthgaur01@gmail.com
amansingh.00321@gmail.com -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Batch250</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value|%>
  <%= value%>
<%end%>
<% if session[:user_id].present? %>
<%= render "layouts/header"%>
<%end%>

<br />
<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<table border = "1">
<tr>
	<th>Photo</th>
	<th>Product Type</th>
	<th>Brand</th>
	<th>Price</th>
	</tr>

	<% @product.each do | j |%>
<tr>
	<td>
		<% if j.images.present?%>
		  <% j.images.each do | image |%>
		    <%= image_tag image.photo(:small)%>
		  <%end%> 
		<%end%>
		</td>
	
 <td><%=  j.product_type %></td>
 <td><%=  j.brand %></td>
 <td><%=  j.price %></td>
 <td><%= link_to "Buy" , trans_product_path(j)%></td>
 <%end%>
 </tr>
</table>

app/views/products/new.html.erb
<table>
	<!--%form_for is a helper %-->
<%= form_for @product do | form | %>
<tr>
<td><%= form.label :product_type%></td>
<td><%= form.text_field :product_type%></td>
</tr>

<tr>
<td><%= form.label :brand%></td>
<td><%= form.text_field :brand%></td>
</tr>

<tr>
<td><%= form.label :price%></td>
<td><%= form.text_field :price%></td>
</tr>
<tr>
	<%= form.fields_for :image do | image | %>
     <td><%= image.label :photo%></td>
     <td><%= image.file_field :photo, :multiple => true%></td>
   <%end%>
</tr>
<tr>
	<td><%= form.submit "Sign up!"%></td>
	</tr>
<%end%>
</table>

<%= link_to "Back" , root_path%>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/products/trans.html.erb
<%= form_for([@product], url: {:controller=>"products",:action=>"trans_pay",:id=>@product}, method: :put) do |f|%>

<%= fields_for :user do |f|%>
<%= f.label :first_name%>
<%= f.text_field :first_name%>
<%= f.label :last_name%>
<%= f.text_field :last_name%>
<%= f.label :company%>
<%= f.text_field :company%>
<%= f.label :email%>
<%= f.text_field :email%>
<%= f.label :phone%>
<%= f.text_field :phone%>
<%= f.label :credit_card_number%>
<%= f.text_field :credit_card_number%>
<%= f.label :expiry_date%>
<%= f.date_select(:date, :order => [:month, :day, :year])%>
<%= f.submit "Pay"%>
<%end%>
<%end%>

app/views/users/_ifadmin.html.erb
<% @user.each do | i | %>
<tr>
	<td><%= image_tag i.image.photo(:small) if i.image.present?%></td>
 <td><%=  i.name %></td>
 <td><%=  i.email %></td>
 <td><%=  i.phone %></td>
 <td><%=  i.address %></td>
 <td><%= link_to "Edit" , edit_user_path(i)%>
 <td><%= link_to "Show" , user_path(i)%>
 	<td><%= link_to "Delete" , i , method: :delete, :data => {:confirm=>"Are you sure!"}%>
 		<td><%= display_name(i.name)%></td>
</tr>
<%end%>

app/views/users/_ifnormaluser.html.erb
<% j = return_user_object%>
<tr>
	<td><%= image_tag j.image.photo(:small) if j.image.present?%></td>
 <td><%=  j.name %></td>
 <td><%=  j.email %></td>
 <td><%=  j.phone %></td>
 <td><%=  j.address %></td>
 <td><%= link_to "Edit" , edit_user_path(j)%>
 <td><%= link_to "Show" , user_path(j)%>
 	<td><%= link_to "Delete" , j , method: :delete, :data => {:confirm=>"Are you sure!"}%>
 		<td><%= display_name(j.name)%></td>
</tr>

app/views/users/edit.html.erb
<table>
	<!--%form_for is a helper %-->
<%= form_for @user do | form | %>
<tr>
<td><%= form.label :name%></td>
<td><%= form.text_field :name%></td>
</tr>

<tr>
<td><%= form.label :email%></td>
<td><%= form.text_field :email%></td>
</tr>
<tr>
<td><%= form.label :phone%></td>
<td><%= form.text_field :phone%></td>
</tr>
<tr>
<td><%= form.label :address%></td>
<td><%= form.text_field :address%></td>
</tr>
<tr>
	<td><%= form.submit "Update"%></td>
	</tr>
<%end%>
</table>
<%= link_to "Back" , users_path%>

app/views/users/index.html.erb
<!--% if !session[:user_id].blank? %--> 

<table border = "1">
<tr>
	<th>Photo</th>
	<th>Name</th>
	<th>Email</th>
	<th>Phone</th>
	<th>Address</th>
	</tr>
<% if  admin?%>
  
    <%= render "ifadmin"%>

<%else%>
  <%= render "ifnormaluser"%>
<%end%>
</table>

<%= link_to "Back" , users_path%>
<%= link_to "Sign up new" , new_user_path%>
 <!-- %end% -->
 <%= will_paginate @user %>

app/views/users/login_page.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%end%>

<table>
	<!--%form_for is a helper %-->
<%= form_for([@user], :url => {:action => "validate_login"}, method: :put) do | form | %>

<tr>
<td><%= form.label :email%></td>
<td><%= form.text_field :email%></td>
</tr>
<tr>
<td><%= form.label :password%></td>
<td><%= form.password_field :password%></td>
</tr>
<tr>
	<td><%= form.submit "Sign In!"%></td>
	</tr>
<%end%>
</table>

<%= link_to "Sign up" , new_user_path%>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%end%>

<table>
	<!--%form_for is a helper %-->
<%= form_for @user do | form | %>
<tr>
<td><%= form.label :name%></td>
<td><%= form.text_field :name%></td>
</tr>

<tr>
<td><%= form.label :email%></td>
<td><%= form.text_field :email%></td>
</tr>

<tr>
<td><%= form.label :password%></td>
<td><%= form.password_field :password%></td>
</tr>
<tr>
<td><%= form.label :confirm_password%></td>
<td><%= form.password_field :confirm_password%></td>
</tr>

<tr>
<td><%= form.label :phone%></td>
<td><%= form.text_field :phone%></td>
</tr>
<tr>
<td><%= form.label :address%></td>
<td><%= form.text_field :address%></td>
</tr>
<tr>
	<%= form.fields_for :image do | image | %>
     <td><%= image.label :photo%></td>
     <td><%= image.file_field :photo%></td>
   <%end%>
</tr>
<tr>
	<td><%= form.submit "Sign up!"%></td>
	</tr>
<%end%>
</table>

<%= link_to "Back" , root_path%>

app/views/users/show.html.erb
<table border = "1">
<tr>
	<th>Name</th>
	<th>Email</th>
	<th>Phone</th>
	<th>Address</th>
	</tr>
<% i = @user%>
<tr>
 <td><%=  i.name %></td>
 <td><%=  i.email %></td>
 <td><%=  i.phone %></td>
 <td><%=  i.address %></td>
 <td><%= link_to "Edit" , edit_user_path(i)%>
</tr>

</table>
<%= link_to "Back" , users_path%>

<!-- <a href=/users> Back-1</a> -->